"""DNS cutover guidance generator — MX/SPF/DKIM/DMARC instructions."""

import logging

log = logging.getLogger("opai-email-migration.dns")

# Provider-specific DNS records
PROVIDER_MX = {
    "hostinger": [
        {"priority": 1, "host": "mx1.hostinger.com"},
        {"priority": 5, "host": "mx2.hostinger.com"},
    ],
    "m365": [
        {"priority": 0, "host": "{domain}.mail.protection.outlook.com"},
    ],
    "gmail": [
        {"priority": 1, "host": "aspmx.l.google.com"},
        {"priority": 5, "host": "alt1.aspmx.l.google.com"},
        {"priority": 5, "host": "alt2.aspmx.l.google.com"},
        {"priority": 10, "host": "alt3.aspmx.l.google.com"},
        {"priority": 10, "host": "alt4.aspmx.l.google.com"},
    ],
}

PROVIDER_SPF = {
    "hostinger": "v=spf1 include:_spf.hostinger.com ~all",
    "m365": "v=spf1 include:spf.protection.outlook.com ~all",
    "gmail": "v=spf1 include:_spf.google.com ~all",
}

PROVIDER_AUTODISCOVER = {
    "hostinger": {
        "imap": "imap.hostinger.com",
        "smtp": "smtp.hostinger.com",
        "imap_port": 993,
        "smtp_port": 465,
    },
    "m365": {
        "imap": "outlook.office365.com",
        "smtp": "smtp.office365.com",
        "imap_port": 993,
        "smtp_port": 587,
    },
}


class DNSGuideGenerator:
    """Generates markdown DNS cutover guide."""

    def __init__(self, source_provider: str, target_provider: str, domain: str):
        self.source = source_provider
        self.target = target_provider
        self.domain = domain

    def generate(self) -> str:
        """Generate complete DNS cutover guide as markdown."""
        sections = [
            self._header(),
            self._pre_cutover_checklist(),
            self._mx_records(),
            self._spf_record(),
            self._dkim_dmarc(),
            self._client_config(),
            self._ttl_strategy(),
            self._verification_commands(),
            self._rollback_plan(),
            self._post_cutover_checklist(),
        ]
        return "\n".join(sections)

    def _header(self) -> str:
        return f"""# DNS Cutover Guide: {self.domain}

**Migration**: {self.source} → {self.target}
**Generated**: Auto-generated by OPAI Email Migration Tool

---
"""

    def _pre_cutover_checklist(self) -> str:
        return """## Pre-Cutover Checklist

- [ ] All email accounts migrated and verified
- [ ] Post-migration verification passed (message counts match)
- [ ] Target email accounts can receive test emails (via direct SMTP)
- [ ] All email clients/devices noted for reconfiguration
- [ ] Calendar/contacts migration handled separately if needed
- [ ] Notify affected users of upcoming change
- [ ] Schedule cutover during low-traffic window
- [ ] Reduce TTL on MX records 24-48 hours before cutover (see TTL Strategy)
- [ ] Take screenshot of current DNS records for rollback reference

---
"""

    def _mx_records(self) -> str:
        target_mx = PROVIDER_MX.get(self.target, [])
        source_mx = PROVIDER_MX.get(self.source, [])

        lines = ["## MX Records", ""]
        lines.append("### Remove (old records):")
        lines.append("```")
        for mx in source_mx:
            host = mx["host"].replace("{domain}", self.domain)
            lines.append(f"  MX  {mx['priority']}  {host}")
        lines.append("```")
        lines.append("")
        lines.append("### Add (new records):")
        lines.append("```")
        for mx in target_mx:
            host = mx["host"].replace("{domain}", self.domain)
            lines.append(f"  MX  {mx['priority']}  {host}")
        lines.append("```")
        lines.append("")
        lines.append("---")
        return "\n".join(lines)

    def _spf_record(self) -> str:
        target_spf = PROVIDER_SPF.get(self.target, "v=spf1 ~all")
        return f"""
## SPF Record

Update the TXT record for `{self.domain}`:

```
TXT  @  "{target_spf}"
```

**Important**: Only one SPF record should exist. Remove any old SPF entries.

---
"""

    def _dkim_dmarc(self) -> str:
        dkim_note = {
            "hostinger": "Hostinger auto-generates DKIM. Check Hostinger hPanel → Email → DKIM for the record value.",
            "m365": "M365 DKIM: Admin Center → Settings → Domains → DKIM. Publish the CNAME records provided.",
            "gmail": "Google Workspace: Admin Console → Apps → Google Workspace → Gmail → Authenticate Email.",
        }
        return f"""
## DKIM

{dkim_note.get(self.target, "Check your email provider's documentation for DKIM setup.")}

After enabling DKIM, add the provided TXT or CNAME record to DNS.

## DMARC

If not already set, add a DMARC record:

```
TXT  _dmarc.{self.domain}  "v=DMARC1; p=none; rua=mailto:postmaster@{self.domain}"
```

Start with `p=none` (monitor mode). After confirming delivery works, tighten to `p=quarantine` or `p=reject`.

---
"""

    def _client_config(self) -> str:
        target_cfg = PROVIDER_AUTODISCOVER.get(self.target, {})
        if not target_cfg:
            return ""

        return f"""
## Email Client Configuration

Update all email clients (Outlook, Thunderbird, mobile) to:

| Setting | Value |
|---------|-------|
| **Incoming (IMAP)** | `{target_cfg.get('imap', 'check provider')}` |
| **IMAP Port** | `{target_cfg.get('imap_port', 993)}` (SSL/TLS) |
| **Outgoing (SMTP)** | `{target_cfg.get('smtp', 'check provider')}` |
| **SMTP Port** | `{target_cfg.get('smtp_port', 465)}` (SSL/TLS) |
| **Authentication** | Normal password |

---
"""

    def _ttl_strategy(self) -> str:
        return """
## TTL Strategy

### 48 hours before cutover:
1. Lower MX record TTL to **300 seconds** (5 minutes)
2. Lower SPF TXT record TTL to **300 seconds**

### At cutover:
1. Update MX records to new values
2. Update SPF record
3. Add DKIM record

### 48 hours after cutover (confirmed working):
1. Raise TTL back to **3600** (1 hour) or **14400** (4 hours)

---
"""

    def _verification_commands(self) -> str:
        return f"""
## Verification Commands

After DNS changes propagate (5-30 minutes with low TTL):

```bash
# Check MX records
dig MX {self.domain} +short

# Check SPF
dig TXT {self.domain} +short | grep spf

# Check DKIM (replace 'default' with your DKIM selector)
dig TXT default._domainkey.{self.domain} +short

# Check DMARC
dig TXT _dmarc.{self.domain} +short

# Test email delivery (send test to external address, then reply back)
# Or use: https://www.mail-tester.com/

# Check propagation globally
# https://dnschecker.org/#MX/{self.domain}
```

---
"""

    def _rollback_plan(self) -> str:
        source_mx = PROVIDER_MX.get(self.source, [])
        lines = ["\n## Rollback Plan", ""]
        lines.append("If issues arise, revert MX records to original values:")
        lines.append("```")
        for mx in source_mx:
            host = mx["host"].replace("{domain}", self.domain)
            lines.append(f"  MX  {mx['priority']}  {host}")
        lines.append("```")
        lines.append("")
        lines.append("With low TTL, rollback takes effect within 5-10 minutes.")
        lines.append("Keep old provider active for at least 7 days after cutover as safety net.")
        lines.append("")
        lines.append("---")
        return "\n".join(lines)

    def _post_cutover_checklist(self) -> str:
        return """
## Post-Cutover Checklist

- [ ] MX records verified (dig MX)
- [ ] SPF record verified
- [ ] DKIM record added and verified
- [ ] Test email: send FROM migrated account → external
- [ ] Test email: send TO migrated account FROM external
- [ ] Test email: internal send between migrated accounts
- [ ] All email clients reconfigured and connected
- [ ] Calendar invites sending correctly
- [ ] Auto-forwarding rules recreated (if any)
- [ ] Mailing lists updated with new server info
- [ ] Monitor bounce/delivery reports for 48 hours
- [ ] Raise TTL back to normal after 48 hours
- [ ] Decommission old provider (after 7+ day safety period)
"""
