<?php
/**
 * OPAI Connector — Auto-Login.
 *
 * Provides a time-limited, HMAC-signed auto-login endpoint.
 * The token is generated by the OP WordPress backend using the
 * connector key as the HMAC secret. Valid for 60 seconds.
 *
 * Uses a query-var URL (not REST API) so cookies can be set before
 * any headers are sent:
 *
 *   site.com/?opai_autologin=1&t={timestamp}&u={username}&sig={hmac}&r={redirect}
 *
 * Flow:
 *   1. OP WP backend generates: HMAC-SHA256(connector_key, "autologin:{timestamp}:{username}")
 *   2. Browser is redirected to the URL above
 *   3. This class validates the signature + timestamp, sets WP auth cookie, redirects.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class OPAI_AutoLogin {

    /** Token validity window in seconds. */
    const TOKEN_TTL = 60;

    /**
     * Handle the auto-login request. Hooked to 'init' (fires before headers).
     */
    public static function handle() {
        if ( empty( $_GET['opai_autologin'] ) ) {
            return;
        }

        $timestamp = isset( $_GET['t'] )   ? sanitize_text_field( $_GET['t'] )   : '';
        $username  = isset( $_GET['u'] )   ? sanitize_text_field( $_GET['u'] )   : '';
        $signature = isset( $_GET['sig'] ) ? sanitize_text_field( $_GET['sig'] ) : '';
        $redirect  = isset( $_GET['r'] )   ? esc_url_raw( $_GET['r'] )           : admin_url();

        // Ensure we're on the canonical domain BEFORE setting any cookies.
        // If the stored site URL has www but WP canonical is non-www (or vice versa),
        // cookies set here won't carry through the redirect. Fix by bouncing to
        // the canonical domain first with the same query params.
        $home_host    = wp_parse_url( home_url(), PHP_URL_HOST );
        $request_host = isset( $_SERVER['HTTP_HOST'] ) ? $_SERVER['HTTP_HOST'] : '';
        if ( $home_host && $request_host && strtolower( $request_host ) !== strtolower( $home_host ) ) {
            $canonical_url = home_url( '/' ) . '?' . $_SERVER['QUERY_STRING'];
            wp_redirect( $canonical_url, 302 );
            exit;
        }

        // Validate required params
        if ( empty( $timestamp ) || empty( $username ) || empty( $signature ) ) {
            wp_die(
                'Missing auto-login parameters.',
                'OPAI Auto-Login Error',
                [ 'response' => 400 ]
            );
        }

        // Check timestamp window
        $now = time();
        $ts  = intval( $timestamp );
        $age = abs( $now - $ts );
        if ( $age > self::TOKEN_TTL ) {
            wp_die(
                sprintf(
                    'Auto-login link has expired (%d seconds old, max %d). Please try again from OP WordPress.',
                    $age, self::TOKEN_TTL
                ),
                'OPAI Auto-Login Expired',
                [ 'response' => 403 ]
            );
        }

        // Validate HMAC signature
        $connector_key = get_option( 'opai_connector_key', '' );
        if ( empty( $connector_key ) ) {
            wp_die(
                'OPAI Connector key not configured on this site.',
                'OPAI Auto-Login Error',
                [ 'response' => 500 ]
            );
        }

        $payload  = "autologin:{$timestamp}:{$username}";
        $expected = hash_hmac( 'sha256', $payload, $connector_key );

        if ( ! hash_equals( $expected, $signature ) ) {
            wp_die(
                'Invalid auto-login signature. The connector key may have changed.',
                'OPAI Auto-Login Error',
                [ 'response' => 403 ]
            );
        }

        // Look up the WordPress user
        $user = get_user_by( 'login', $username );
        if ( ! $user ) {
            $user = get_user_by( 'email', $username );
        }
        if ( ! $user ) {
            wp_die(
                'WordPress user not found: ' . esc_html( $username ),
                'OPAI Auto-Login Error',
                [ 'response' => 404 ]
            );
        }

        // Require administrator
        if ( ! user_can( $user, 'manage_options' ) ) {
            wp_die(
                'User does not have administrator privileges.',
                'OPAI Auto-Login Error',
                [ 'response' => 403 ]
            );
        }

        // Set the auth cookie and redirect
        wp_set_auth_cookie( $user->ID, true );
        wp_set_current_user( $user->ID );

        nocache_headers();

        // Build canonical redirect using WordPress's own home_url() to ensure
        // cookies (set on this domain) match the redirect domain.
        // This avoids www vs non-www mismatches that break auth cookies.
        $final_redirect = $redirect;
        $parsed = wp_parse_url( $redirect );
        if ( ! empty( $parsed['path'] ) ) {
            $canonical = home_url( $parsed['path'] );
            if ( ! empty( $parsed['query'] ) ) {
                $canonical .= '?' . $parsed['query'];
            }
            if ( ! empty( $parsed['fragment'] ) ) {
                $canonical .= '#' . $parsed['fragment'];
            }
            $final_redirect = $canonical;
        }

        wp_safe_redirect( $final_redirect );
        exit;
    }
}
