#!/bin/bash
# OPAI Server — Headless Virtual Display Setup
# Forces NVIDIA GPU to maintain a virtual display when no monitor is connected.
# This allows RustDesk (and other remote desktop tools) to mirror the desktop.
#
# Usage:
#   sudo ./scripts/setup-headless-display.sh [resolution]
#
# Examples:
#   sudo ./scripts/setup-headless-display.sh           # Default: 2560x1440
#   sudo ./scripts/setup-headless-display.sh 1920x1080
#   sudo ./scripts/setup-headless-display.sh 3840x2160
#   sudo ./scripts/setup-headless-display.sh remove     # Remove config and restore default
#
# Recovery (if display breaks, SSH in):
#   sudo rm /etc/X11/xorg.conf && sudo systemctl restart gdm

set -euo pipefail

XORG_CONF="/etc/X11/xorg.conf"
RESOLUTION="${1:-2560x1440}"

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Must run as root (sudo)"
    exit 1
fi

# Remove mode
if [ "$RESOLUTION" = "remove" ]; then
    if [ -f "$XORG_CONF" ]; then
        rm "$XORG_CONF"
        echo "Removed $XORG_CONF"
        echo "Restart display manager to apply: sudo systemctl restart gdm"
    else
        echo "No $XORG_CONF to remove"
    fi
    exit 0
fi

# Validate resolution format
if ! echo "$RESOLUTION" | grep -qE '^[0-9]+x[0-9]+$'; then
    echo "ERROR: Invalid resolution format. Use WIDTHxHEIGHT (e.g., 2560x1440)"
    exit 1
fi

# Check for NVIDIA driver
if ! /usr/sbin/lsmod | grep -q 'nvidia'; then
    echo "ERROR: NVIDIA driver not loaded. This script is for NVIDIA GPUs only."
    exit 1
fi

# Backup existing config
if [ -f "$XORG_CONF" ]; then
    cp "$XORG_CONF" "${XORG_CONF}.bak.$(date +%s)"
    echo "Backed up existing xorg.conf"
fi

cat > "$XORG_CONF" << XORGEOF
# OPAI Server — Headless virtual display config
# Generated by setup-headless-display.sh on $(date -Iseconds)
# Resolution: ${RESOLUTION}
# Forces NVIDIA to keep DVI-I-1 active without a physical monitor
# Safe to leave in place even WITH a monitor connected (or with dummy plug)

Section "Device"
    Identifier     "GPU0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 980"
    Option         "ConnectedMonitor" "DFP-0"
    Option         "AllowEmptyInitialConfiguration" "true"
    Option         "ModeValidation" "NoDFPNativeResolutionCheck,NoVirtualSizeCheck,NoMaxPClkCheck,NoEdidMaxPClkCheck,AllowNon60HzDFPModes"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "GPU0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "MetaModes" "DFP-0: ${RESOLUTION} +0+0"
    Option         "DPI" "96 x 96"
    SubSection     "Display"
        Depth       24
        Modes      "${RESOLUTION}"
    EndSubSection
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Virtual"
    ModelName      "Virtual Display"
    HorizSync       28.0-100.0
    VertRefresh     48.0-75.0
    Option         "DPMS" "false"
EndSection
XORGEOF

echo "Created $XORG_CONF with virtual display at ${RESOLUTION}"
echo ""
echo "To apply now (will log you out of GUI):"
echo "  sudo systemctl restart gdm"
echo ""
echo "To remove later:"
echo "  sudo $0 remove"
echo "  sudo systemctl restart gdm"
